"""empty message

Revision ID: 5d8b73d3fa4e
Revises: 4dd1015e0131
Create Date: 2020-04-28 15:51:10.566656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8b73d3fa4e'
down_revision = '4dd1015e0131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_start', sa.DateTime(), nullable=False),
    sa.Column('s_artist', sa.Integer(), nullable=False),
    sa.Column('s_venue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_artist'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['s_venue'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('Show')
    # ### end Alembic commands ###
